# Generated by Django 3.0.7 on 2020-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200609_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
    ]
